library(dplyr)
setwd("C:/RstudioGithub/datasciencecoursera/ExploratoryDataAnalysis/Week 1")

elek <- tbl_df(read.csv(file = "household_power_consumption.txt", sep = ";"))
elek <- subset(elek, Date == c("1/2/2007", "2/2/2007"))
elek$Date <- strptime(elek$Date, format = "%d/%m/%Y")
elek$Time <- format(elek$Time, "%H:%M:%S")
elek$datetime <- as.POSIXct(paste(elek$Date, elek$Time, format="%Y-%m-%d %H:%M:%S"))
elek$Voltage <- as.numeric(elek$Voltage)
elek$Global_reactive_power <- as.numeric(elek$Global_reactive_power)
elek$Global_active_power <- as.numeric(elek$Global_active_power)

png(file = "plot4.png")
par(mfrow = c(2, 2), mar = c(4, 4, 1, 1))
plot(elek$datetime, elek$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(elek$datetime, elek$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(elek$datetime,elek$Sub_metering_1,type="l", ylab = "Energy sub metering", xlab = "")
lines(elek$datetime,elek$Sub_metering_2,col="red")
lines(elek$datetime,elek$Sub_metering_3,col="blue")
legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
plot(elek$datetime, elek$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
